### ISSUE TITLE
Error when compiling App Bundle

### ISSUE THREAD

**Issue by samatzp** [MadBrains/App-Runner-Flutter#1]
Unhandled exception:
Unexpected type InvalidType InvalidType(<invalid>)
#0      TypesBuilder.fromStaticType (package:vm/transformations/type_flow/types.dart:103:7)
#1      SummaryCollector._staticType (package:vm/transformations/type_flow/summary_collector.dart:1192:21)
#2      SummaryCollector.visitConditionalExpression (package:vm/transformations/type_flow/summary_collector.dart:1491:27)
#3      ConditionalExpression.accept (package:kernel/ast.dart:6684:44)
#4      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#5      SummaryCollector.visitLet (package:vm/transformations/type_flow/summary_collector.dart:1538:12)
#6      Let.accept (package:kernel/ast.dart:8395:44)
#7      SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#8      SummaryCollector.visitConditionalExpression (package:vm/transformations/type_flow/summary_collector.dart:1483:18)
#9      ConditionalExpression.accept (package:kernel/ast.dart:6684:44)
#10     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#11     SummaryCollector.visitReturnStatement (package:vm/transformations/type_flow/summary_collector.dart:2101:43)
#12     ReturnStatement.accept (package:kernel/ast.dart:9869:43)
#13     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#14     SummaryCollector._handleNestedFunctionNode (package:vm/transformations/type_flow/summary_collector.dart:1274:5)
#15     SummaryCollector.visitFunctionExpression (package:vm/transformations/type_flow/summary_collector.dart:1507:5)
#16     FunctionExpression.accept (package:kernel/ast.dart:8284:44)
#17     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#18     SummaryCollector._visitArguments (package:vm/transformations/type_flow/summary_collector.dart:879:16)
#19     SummaryCollector.visitInstanceInvocation (package:vm/transformations/type_flow/summary_collector.dart:1605:18)
#20     InstanceInvocation.accept (package:kernel/ast.dart:5505:44)
#21     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#22     SummaryCollector.visitConditionalExpression (package:vm/transformations/type_flow/summary_collector.dart:1487:18)
#23     ConditionalExpression.accept (package:kernel/ast.dart:6684:44)
#24     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#25     SummaryCollector.visitLet (package:vm/transformations/type_flow/summary_collector.dart:1538:12)
#26     Let.accept (package:kernel/ast.dart:8395:44)
#27     SummaryCollector._visit (package:vm/transformations/type_flow/summary_collector.dart:861:44)
#28     SummaryCollector.visitVariableDeclaration (package:vm/transformations/type_flow/summary_collector.dart:2179:43)
#29     VariableDeclaration.accept (package:kernel/ast.dart:10436:43)
#30     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#31     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#32     List.forEach (dart:core-patch/growable_array.dart:410:8)
#33     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#34     Block.accept (package:kernel/ast.dart:8890:43)
#35     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#36     SummaryCollector.visitTryCatch (package:vm/transformations/type_flow/summary_collector.dart:2140:5)
#37     TryCatch.accept (package:kernel/ast.dart:9923:43)
#38     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#39     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#40     List.forEach (dart:core-patch/growable_array.dart:410:8)
#41     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#42     Block.accept (package:kernel/ast.dart:8890:43)
#43     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#44     SummaryCollector.visitLabeledStatement (package:vm/transformations/type_flow/summary_collector.dart:2090:5)
#45     LabeledStatement.accept (package:kernel/ast.dart:9100:43)
#46     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#47     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#48     List.forEach (dart:core-patch/growable_array.dart:410:8)
#49     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#50     Block.accept (package:kernel/ast.dart:8890:43)
#51     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#52     SummaryCollector.visitTryCatch (package:vm/transformations/type_flow/summary_collector.dart:2140:5)
#53     TryCatch.accept (package:kernel/ast.dart:9923:43)
#54     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#55     SummaryCollector.visitTryFinally (package:vm/transformations/type_flow/summary_collector.dart:2167:5)
#56     TryFinally.accept (package:kernel/ast.dart:10099:43)
#57     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#58     SummaryCollector._handleNestedFunctionNode (package:vm/transformations/type_flow/summary_collector.dart:1274:5)
#59     SummaryCollector.visitFunctionDeclaration (package:vm/transformations/type_flow/summary_collector.dart:2064:5)
#60     FunctionDeclaration.accept (package:kernel/ast.dart:10507:43)
#61     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#62     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart)
#63     List.forEach (dart:core-patch/growable_array.dart:410:8)
#64     SummaryCollector.visitBlock (package:vm/transformations/type_flow/summary_collector.dart:1962:21)
#65     Block.accept (package:kernel/ast.dart:8890:43)
#66     SummaryCollector._visitWithoutResult (package:vm/transformations/type_flow/summary_collector.dart:864:10)
#67     SummaryCollector.createSummary (package:vm/transformations/type_flow/summary_collector.dart:765:9)
#68     TypeFlowAnalysis.getSummary (package:vm/transformations/type_flow/analysis.dart:1533:52)
#69     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:298:42)
#70     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#71     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#72     _DispatchableInvocation.process.<anonymous closure> (package:vm/transformations/type_flow/analysis.dart:449:44)
#73     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:539:8)
#74     _DispatchableInvocation.process (package:vm/transformations/type_flow/analysis.dart:423:12)
#75     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#76     TypeFlowAnalysis.applyCall (package:vm/transformations/type_flow/analysis.dart:1670:23)
#77     Call.apply (package:vm/transformations/type_flow/summary.dart:268:31)
#78     Summary.apply (package:vm/transformations/type_flow/summary.dart:724:33)
#79     _DirectInvocation._processFunction (package:vm/transformations/type_flow/analysis.dart:307:24)
#80     _DirectInvocation.process (package:vm/transformations/type_flow/analysis.dart:226:14)
#81     _WorkList.processInvocation (package:vm/transformations/type_flow/analysis.dart:1429:27)
#82     _WorkList.process (package:vm/transformations/type_flow/analysis.dart:1371:7)
#83     TypeFlowAnalysis.process (package:vm/transformations/type_flow/analysis.dart:1551:14)
#84     transformComponent (package:vm/transformations/type_flow/transformer.dart:87:20)
#85     runGlobalTransformations (package:vm/kerne
l_front_end.dart:454:20)
#86     compileToKernel (package:vm/kernel_front_end.dart:376:11)
<asynchronous suspension>
#87     FrontendCompiler.compile (package:frontend_server/frontend_server.dart:541:17)
<asynchronous suspension>
#88     starter (package:flutter_frontend_server/server.dart:85:12)
<asynchronous suspension>
#89     main (file:///C:/b/s/w/ir/cache/builder/src/flutter/flutter_frontend_server/bin/starter.dart:13:24)
<asynchronous suspension>

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1070

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 50s
Running Gradle task 'bundleRelease'...                             51,5s
Gradle task bundleRelease failed with exit code 1
Process finished with exit code 1

**Comment by samatzp** [comment]
sorry error was in other side) Cool package Thank you!!!

**Comment by gbelfingerivs** [comment]
@samatzhusup what was the error in your case?
I am getting exactly the same error as you in our project, I have no idea how to fix it, everything was working correctly and at one point it just stopped working...

**Comment by samatzp** [comment]
@gbelfingerivs in my case the error was when initializing the Qonversion package.
Maybe help you fully reinstall app.

**Comment by gbelfingerivs** [comment]
@samatzhusup we are not using Qonversion at all. Seems that the build got broken after one of the commits in our codebase, which does not make any sense.

How did you fix it and what do you mean by fully reinstall app?
I tried with flutter clean and deleting all temp data including pubspec.lock
